services:
  gaboWebService:
    build: .
    image: gabo/gabowebservice
    container_name: gaboWebService
    volumes:
      - ../data:/usr/src/app/data
    ports:
      - "3000:3000"

networks:
  nginx_net:
    external: true